### ISSUE TITLE
there is not published_results/vocabulary/dic_pickle  

### ISSUE THREAD

**Issue by natalymr** [spcl/ncc#2]
I ran `python train_task_classifyapp.py` with default parameters, so, there was the needed file,  `published_resilts/emb.p`, but there was not a folder `published_results/vocabulary`. 

That's why I had the error like this:
```
FileNotFoundError: [Errno 2] No such file or directory: 'published_results/vocabulary/dic_pickle'
```

**Comment by tbennun** [comment]
The file is published as well, but it was too large to include in the git repository itself. It’s linked in the README: https://github.com/spcl/ncc/tree/master/published_results

Here is the direct link to the vocabulary files: https://polybox.ethz.ch/index.php/s/AWKd60qR63yViH8

**Comment by natalymr** [comment]
> The file is published as well, but it was too large to include in the git repository itself. It’s linked in the README: https://github.com/spcl/ncc/tree/master/published_results
> 
> Here is the direct link to the vocabulary files: https://polybox.ethz.ch/index.php/s/AWKd60qR63yViH8

Thanks for the quick response!

Now everything works. thanks again

**Comment by tbennun** [comment]
No problem 👍

**Comment by tszdanger** [comment]
Good for your information!THX
