### ISSUE TITLE
[train_inst2vec.py] need to be more than one folder with raw data in data/ 

### ISSUE THREAD

**Issue by natalymr** [spcl/ncc#3]
To tell the truth, it is not clear for me why in `train_inst2vec.py` there is such condition (45-47 rows):
```
if FLAGS.data == "data" and len(os.listdir(data_folder)) <= 1:
            # Generate the data set
            print('Folder', data_folder, 'is empty - preparing to download training data')
```

For example, I downloaded `BLAS` dataset. So, my `data`-folder looks like `data/blas/*.ll`.
And after running `python train_inst2vec.py` I got something like this
```
Folder data is empty - preparing to download training data
Downloading AMD data set...
``` 

Why folders with raw data need to be more than one?
Depending on what a data should be placed in several folders?

**Comment by tbennun** [comment]
The reason we have different data folders is that different source code repositories have different compilation instructions. The sub-folders also remain for the LLVM IR files so that the compilation or existence of the files can be tracked.

Does this answer the question?

**Comment by natalymr** [comment]
Hello, @tbennun!

To tell the truth, in sum I just used your pre-trained embedding for instructions.

**Comment by tbennun** [comment]
Closing the issue due to old age. Please reopen if necessary!
