### ISSUE TITLE
[inst2vec_evaluate.py] IndexError : list index out of range in analogies

### ISSUE THREAD

**Issue by uisanglee** [spcl/ncc#42]
Hi, I'm working on a project that makes Go code into llvm IR using gollvm(https://go.googlesource.com/gollvm)
After get IR from Go codes, I made test folder having go IRs to run train_inst2vec.py.
But there was an error that analogies list don't have any value. 

Can I know what the analogies do?
If can, I want to know how to solve the Error attached in this issue.

![test](https://user-images.githubusercontent.com/62749977/196375920-80c52ec5-f642-4a6e-a3d6-e9216f51034f.png)

Thanks.

**Comment by HosoyaKenn** [comment]
Hey！
Have you ever resolve this problem？I also encountered it
