### ISSUE TITLE
No way to convert .class files to .ll files

### ISSUE THREAD

**Issue by natalymr** [spcl/ncc#5]
It seems like there is no any good way to convert java bytecode to llvm bitcode.

All projects that I've discovered and which are dedicated to this topic are either outdated or abandoned.

Could you please suggest some way to make this conversion?

**Comment by tbennun** [comment]
Although we did not use Java source code in our experiments, I assume you can use something like the (now defunct) GCJ and [DragonEgg](https://dragonegg.llvm.org/), or the retired [VMkit](http://vmkit.llvm.org/).

If you find anything, please let us know!
