### ISSUE TITLE
train_task_classify is searching for .rec in wrong folder

### ISSUE THREAD

**Issue by sipian** [spcl/ncc#6]
When I am running `train_task_classify.py`

https://github.com/spcl/ncc/blob/4e9eaeb6e7d3687cc73e73ae0fdf513f4e429e83/train_task_classifyapp.py#L285-L291

This assertion is failing (`seq_files` list is empty).
This is because the `.rec` files are generated in separate folders prefixed by `seq`.
https://github.com/spcl/ncc/blob/4e9eaeb6e7d3687cc73e73ae0fdf513f4e429e83/task_utils.py#L259-L269

But `train_task_classify` is searching for .rec files in the original IR folder `ir_train`.

**Comment by natalymr** [comment]
Hello, @sipian 

I had the same problem and used a workaround described here, the second message: https://github.com/spcl/ncc/issues/4
i.e. just change a directory.

**Comment by tbennun** [comment]
Thanks for reporting @sipian and thank you for mentioning the workaround, @natalymr.

I'll try with a clean build and replace the lines as necessary.

**Comment by tbennun** [comment]
@sipian Did #9 fix the issue?

**Comment by tbennun** [comment]
Closing the issue due to old age. Please reopen if necessary!
