### ISSUE TITLE
The difference between XFG and PDG?

### ISSUE THREAD

**Issue by coder-chenzhi** [spcl/ncc#8]
The corresponding paper claim that a novel representation of IR, called conteXtual Flow Graph (XFG), was propsed. However, I realize that this representation is similar with traditional [Program Dependence Graph](https://en.wikipedia.org/wiki/Program_Dependence_Graph).

**Comment by tbennun** [comment]
Good question. In the paper, there is a direct comparison between XFGs and PDGs. In particular, the XFG can be generated in a linear time with the number of statements, where PDGs are generated in squared time w.r.t. the number of statements. In large codebases, such as TensorFlow, this makes a huge difference.

**Comment by coder-chenzhi** [comment]
@tbennun Thanks for your explanation. I have looked into the creation process of XFG and realize the differences between PDG:
- The data dependence only resides in the statements belongs to the same basic block. The exceptions are the edges between identifiers and their root nodes.
- The control dependence is more like the edge in CFG (Control Flow Graph), rather than the edge the Control Dependence Graph. The latter is build on top of Dominator Tree, which is time-consuming.

**Comment by tbennun** [comment]
Yes, both statements are correct.

Since this is resolved, I'll close the issue now.
